import { FileDown } from 'lucide-react';

interface ExportReportButtonProps {
  healthScore: number;
  forestValue: string;
  riskLevel: string;
  parcelName: string;
}

export function ExportReportButton({
  healthScore,
  forestValue,
  riskLevel,
  parcelName,
}: ExportReportButtonProps) {
  const handleExport = () => {
    const today = new Date().toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    });

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>BeetleSense Forest Report — ${parcelName}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'DM Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      color: #1a2e1a;
      background: #fff;
      padding: 48px 32px;
      max-width: 700px;
      margin: 0 auto;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 2px solid #1B5E20;
    }
    .logo {
      font-size: 22px;
      font-weight: 700;
      color: #1B5E20;
      letter-spacing: -0.5px;
    }
    .logo span {
      font-weight: 400;
      color: #6b7c6b;
    }
    .date {
      font-size: 13px;
      color: #6b7c6b;
    }
    h1 {
      font-family: 'Cormorant Garamond', Georgia, serif;
      font-size: 28px;
      font-weight: 600;
      color: #1a2e1a;
      margin-bottom: 8px;
    }
    .subtitle {
      font-size: 14px;
      color: #6b7c6b;
      margin-bottom: 32px;
    }
    .grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
      margin-bottom: 32px;
    }
    .card {
      border: 1px solid #e2e8e2;
      border-radius: 12px;
      padding: 20px;
      background: #f8faf8;
    }
    .card-label {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: #6b7c6b;
      margin-bottom: 8px;
    }
    .card-value {
      font-size: 28px;
      font-weight: 700;
      color: #1B5E20;
    }
    .card-value.warn {
      color: #d97706;
    }
    .card-note {
      font-size: 12px;
      color: #6b7c6b;
      margin-top: 4px;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e2e8e2;
      font-size: 11px;
      color: #9ca39c;
      text-align: center;
    }
    .print-btn {
      display: block;
      margin: 32px auto 0;
      padding: 10px 28px;
      background: #1B5E20;
      color: #fff;
      border: none;
      border-radius: 8px;
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
    }
    .print-btn:hover {
      opacity: 0.9;
    }
    @media print {
      .print-btn { display: none; }
      body { padding: 24px; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">BeetleSense<span>.ai</span></div>
    <div class="date">${today}</div>
  </div>

  <h1>Forest Report: ${parcelName}</h1>
  <p class="subtitle">Summary of forest health, value and risk assessment.</p>

  <div class="grid">
    <div class="card">
      <div class="card-label">Health Score</div>
      <div class="card-value">${healthScore}/100</div>
      <div class="card-note">${healthScore >= 70 ? 'Good condition' : healthScore >= 40 ? 'Needs attention' : 'Critical'}</div>
    </div>
    <div class="card">
      <div class="card-label">Risk Level</div>
      <div class="card-value ${riskLevel !== 'Low' ? 'warn' : ''}">${riskLevel}</div>
      <div class="card-note">Bark beetle & storm risk</div>
    </div>
    <div class="card">
      <div class="card-label">Forest Value</div>
      <div class="card-value">${forestValue}</div>
      <div class="card-note">Estimated timber + carbon</div>
    </div>
    <div class="card">
      <div class="card-label">Parcel</div>
      <div class="card-value" style="font-size: 22px;">${parcelName}</div>
      <div class="card-note">Primary forest holding</div>
    </div>
  </div>

  <button class="print-btn" onclick="window.print()">Print this report</button>

  <div class="footer">
    Generated by BeetleSense.ai &mdash; ${today}
  </div>
</body>
</html>`;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
    }
  };

  return (
    <button
      onClick={handleExport}
      className="mt-2 flex items-center gap-1.5 text-[11px] text-[var(--text3)] hover:text-[var(--green)] transition-colors"
    >
      <FileDown size={13} />
      Export report
    </button>
  );
}
