/**
 * PrintableReport — Printable HTML report template component.
 *
 * Renders a clean, white-background report optimized for browser printing.
 * Includes BeetleSense header with green stripe, table of contents, per-parcel
 * sections with CSS-only health gauges, species composition bars, and risk indicators.
 *
 * Fully self-contained — no external project imports.
 */

import { useMemo } from 'react';

// ─── Types ───

export interface PrintableParcel {
  id: string;
  name: string;
  municipality: string;
  areaHectares: number;
  speciesMix: { species: string; pct: number }[];
  healthScore: number;
  healthTrend: 'improving' | 'stable' | 'declining';
  beetleRisk: 'low' | 'medium' | 'high' | 'critical';
  lastSurveyDate: string;
  treesScanned: number;
  infectedTrees: number;
  deadTrees: number;
  timberVolumeM3: number;
  timberValueSEK: number;
  carbonTonsCO2: number;
  ndviAvg: number;
  recommendations: string[];
  riskFactors: string[];
  historicalScores: { month: string; score: number }[];
  coordinates?: { lat: number; lng: number };
  standAge?: number;
}

export type PrintLanguage = 'sv' | 'en';
export type PrintCoordinateSystem = 'WGS84' | 'SWEREF99';

export interface PrintableReportProps {
  type: 'parcel-summary' | 'portfolio-overview' | 'survey-report' | 'timber-inventory' | 'health-assessment';
  parcels: PrintableParcel[];
  language: PrintLanguage;
  coordinateSystem: PrintCoordinateSystem;
  userName?: string;
  generatedAt?: string;
  surveyId?: string;
  surveyDate?: string;
  droneModel?: string;
}

// ─── Helpers ───

const LABELS: Record<PrintLanguage, Record<string, string>> = {
  sv: {
    parcelSummary: 'Skiftesammanfattning',
    portfolioOverview: 'Portfoljsammanfattning',
    surveyReport: 'Droneinventeringsrapport',
    timberInventory: 'Virkesforradsinventering',
    healthAssessment: 'Skogshalsobedoming',
    toc: 'Innehallsforteckning',
    parcelOverview: 'Skiftesoverblick',
    area: 'Areal',
    hectares: 'hektar',
    municipality: 'Kommun',
    healthScore: 'Halsoindex',
    healthTrend: 'Halsotrend',
    beetleRisk: 'Barkborrerisk',
    species: 'Tradeslagsfordelning',
    lastSurvey: 'Senaste inventering',
    treesScanned: 'Trad inventerade',
    infectedTrees: 'Infekterade trad',
    deadTrees: 'Doda trad',
    timberVolume: 'Virkesforrad',
    timberValue: 'Virkesvarде',
    carbon: 'Kolbindning',
    ndvi: 'Genomsnittligt NDVI',
    recommendations: 'Rekommendationer',
    riskFactors: 'Riskfaktorer',
    trend12: 'Halsoindexutveckling',
    summary: 'Sammanfattande statistik',
    totalArea: 'Total areal',
    avgHealth: 'Genomsnittligt halsoindex',
    totalVolume: 'Totalt virkesforrad',
    totalValue: 'Totalt virkesvarде',
    parcelsIncluded: 'Antal skiften',
    page: 'Sida',
    of: 'av',
    date: 'Datum',
    generatedBy: 'Genererad av',
    confidential: 'Konfidentiellt',
    disclaimer: 'Denna rapport ar automatiskt genererad och bor verifieras av en certifierad skoglig radgivare.',
    surveyDetails: 'Inventeringsdetaljer',
    surveyId: 'Inventerings-ID',
    surveyDate: 'Inventeringsdatum',
    droneModel: 'Dronemodell',
    detectionSummary: 'Detektionssammanfattning',
    infectionRate: 'Infektionsgrad',
    riskOverview: 'Riskoverblick',
    improving: 'Forbattras',
    stable: 'Stabil',
    declining: 'Forsamras',
    low: 'Lag',
    medium: 'Medel',
    high: 'Hog',
    critical: 'Kritisk',
  },
  en: {
    parcelSummary: 'Parcel Summary',
    portfolioOverview: 'Portfolio Overview',
    surveyReport: 'Drone Survey Report',
    timberInventory: 'Timber Inventory Report',
    healthAssessment: 'Forest Health Assessment',
    toc: 'Table of Contents',
    parcelOverview: 'Parcel Overview',
    area: 'Area',
    hectares: 'hectares',
    municipality: 'Municipality',
    healthScore: 'Health Score',
    healthTrend: 'Health Trend',
    beetleRisk: 'Beetle Risk',
    species: 'Species Composition',
    lastSurvey: 'Last Survey',
    treesScanned: 'Trees Scanned',
    infectedTrees: 'Infected Trees',
    deadTrees: 'Dead Trees',
    timberVolume: 'Timber Volume',
    timberValue: 'Timber Value',
    carbon: 'Carbon Sequestration',
    ndvi: 'Average NDVI',
    recommendations: 'Recommendations',
    riskFactors: 'Risk Factors',
    trend12: 'Health Score Trend',
    summary: 'Summary Statistics',
    totalArea: 'Total Area',
    avgHealth: 'Average Health Score',
    totalVolume: 'Total Timber Volume',
    totalValue: 'Total Timber Value',
    parcelsIncluded: 'Parcels Included',
    page: 'Page',
    of: 'of',
    date: 'Date',
    generatedBy: 'Generated by',
    confidential: 'Confidential',
    disclaimer: 'This report is auto-generated and should be verified by a certified forestry professional.',
    surveyDetails: 'Survey Details',
    surveyId: 'Survey ID',
    surveyDate: 'Survey Date',
    droneModel: 'Drone Model',
    detectionSummary: 'Detection Summary',
    infectionRate: 'Infection Rate',
    riskOverview: 'Risk Overview',
    improving: 'Improving',
    stable: 'Stable',
    declining: 'Declining',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    critical: 'Critical',
  },
};

const SPECIES_COLORS: Record<string, string> = {
  Gran: '#166534', Spruce: '#166534',
  Tall: '#854d0e', Pine: '#854d0e',
  Bjork: '#2563eb', Birch: '#2563eb',
  Ek: '#7c3aed', Oak: '#7c3aed',
  Asp: '#0891b2', Aspen: '#0891b2',
};

function fmtNum(v: number, d: number, lang: PrintLanguage): string {
  if (lang === 'sv') {
    const parts = v.toFixed(d).split('.');
    const int = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, '\u00A0');
    return d > 0 && parts[1] ? `${int},${parts[1]}` : int;
  }
  return v.toLocaleString('en-US', { minimumFractionDigits: d, maximumFractionDigits: d });
}

function fmtSEK(v: number, lang: PrintLanguage): string {
  return lang === 'sv' ? `${fmtNum(v, 0, lang)} kr` : `SEK ${fmtNum(v, 0, lang)}`;
}

function fmtDate(d: string | undefined, lang: PrintLanguage): string {
  if (!d) return new Date().toLocaleDateString(lang === 'sv' ? 'sv-SE' : 'en-GB');
  try { return new Date(d).toLocaleDateString(lang === 'sv' ? 'sv-SE' : 'en-GB'); } catch { return d; }
}

function scoreColor(s: number): string {
  if (s >= 70) return '#166534';
  if (s >= 40) return '#b45309';
  return '#dc2626';
}

function riskColor(r: string): string {
  if (r === 'low') return '#166534';
  if (r === 'medium') return '#b45309';
  return '#dc2626';
}

function specColor(s: string): string {
  return SPECIES_COLORS[s] ?? '#6b7280';
}

function titleForType(type: PrintableReportProps['type'], lang: PrintLanguage): string {
  const key = type === 'parcel-summary' ? 'parcelSummary'
    : type === 'portfolio-overview' ? 'portfolioOverview'
    : type === 'survey-report' ? 'surveyReport'
    : type === 'timber-inventory' ? 'timberInventory'
    : 'healthAssessment';
  return LABELS[lang][key];
}

// ─── Sub-components ───

function ReportHeader({ language, userName, generatedAt }: { language: PrintLanguage; userName?: string; generatedAt?: string }) {
  return (
    <div className="flex items-center justify-between pb-3 mb-4 border-b-[3px] border-[#166534] print:border-b-[3px]">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 bg-[#166534] rounded-lg flex items-center justify-center text-white font-bold text-lg font-serif">
          B
        </div>
        <div>
          <h1 className="text-base font-serif font-bold text-[#166534] leading-tight">BeetleSense.ai</h1>
          <p className="text-[9px] text-gray-500">Forest Intelligence Platform</p>
        </div>
      </div>
      <div className="text-right text-[9px] text-gray-500">
        <div>{LABELS[language].date}: {fmtDate(generatedAt, language)}</div>
        {userName && <div>{LABELS[language].generatedBy}: {userName}</div>}
      </div>
    </div>
  );
}

function GreenStripe() {
  return <div className="h-1 bg-gradient-to-r from-[#166534] to-[#22c55e] rounded-sm mb-5 print:bg-[#166534]" />;
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="font-serif text-[13px] font-bold text-[#166534] border-b border-gray-300 pb-1 mt-5 mb-2.5 print:mt-4">
      {children}
    </h3>
  );
}

function KVRow({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="flex py-[3px] text-[10.5px]">
      <span className="w-[180px] text-gray-500 shrink-0">{label}</span>
      <span className="text-gray-900 font-medium">{String(value)}</span>
    </div>
  );
}

function HealthGauge({ score }: { score: number }) {
  const color = scoreColor(score);
  return (
    <div className="border border-gray-200 rounded-lg p-3 text-center">
      <div className="relative w-20 h-10 mx-auto mb-1">
        <div className="w-20 h-10 rounded-t-full bg-gray-200 overflow-hidden relative">
          <div
            className="absolute bottom-0 left-0 w-full rounded-t-full"
            style={{ height: `${score}%`, background: color, opacity: 0.3 }}
          />
        </div>
        <div
          className="absolute bottom-0 left-0 right-0 text-center text-base font-bold font-mono"
          style={{ color }}
        >
          {score}
        </div>
      </div>
      <div className="text-[9px] text-gray-500 uppercase tracking-wide">Health Score</div>
    </div>
  );
}

function SpeciesBar({ speciesMix }: { speciesMix: { species: string; pct: number }[] }) {
  return (
    <div>
      <div className="flex h-6 rounded-md overflow-hidden my-2">
        {speciesMix.map((s) => (
          <div
            key={s.species}
            className="flex items-center justify-center text-[8px] font-semibold text-white"
            style={{ width: `${s.pct}%`, background: specColor(s.species), minWidth: '16px' }}
          >
            {s.pct > 10 ? `${s.pct}%` : ''}
          </div>
        ))}
      </div>
      <div className="flex flex-wrap gap-3 mt-1.5 text-[9px]">
        {speciesMix.map((s) => (
          <div key={s.species} className="flex items-center gap-1">
            <span className="w-2 h-2 rounded-full inline-block" style={{ background: specColor(s.species) }} />
            {s.species} {s.pct}%
          </div>
        ))}
      </div>
    </div>
  );
}

function RiskBadge({ risk, language }: { risk: string; language: PrintLanguage }) {
  const color = riskColor(risk);
  const label = LABELS[language][risk] ?? risk;
  return (
    <span
      className="inline-block px-2.5 py-0.5 rounded-[10px] text-[9px] font-semibold uppercase tracking-wide"
      style={{ background: `${color}20`, color }}
    >
      {label}
    </span>
  );
}

function ScoreTrendChart({ scores }: { scores: { month: string; score: number }[] }) {
  if (scores.length === 0) return null;
  const max = Math.max(...scores.map((s) => s.score), 100);
  return (
    <div className="flex items-end gap-[2px] h-[60px] my-2">
      {scores.map((s, i) => (
        <div
          key={i}
          className="flex-1 min-w-[8px] rounded-t-sm relative"
          style={{
            height: `${(s.score / max) * 100}%`,
            background: scoreColor(s.score),
            opacity: 0.8,
          }}
        >
          <span className="absolute -bottom-3.5 left-1/2 -translate-x-1/2 text-[6px] text-gray-400 whitespace-nowrap">
            {s.month}
          </span>
        </div>
      ))}
    </div>
  );
}

function ReportFooter({ pageNum, totalPages, language, generatedAt }: {
  pageNum: number;
  totalPages: number;
  language: PrintLanguage;
  generatedAt?: string;
}) {
  return (
    <div className="mt-6 pt-2 border-t border-gray-300">
      <div className="flex justify-between text-[8px] text-gray-400">
        <span>BeetleSense.ai &mdash; {LABELS[language].confidential}</span>
        <span>{fmtDate(generatedAt, language)}</span>
        <span>{LABELS[language].page} {pageNum} {LABELS[language].of} {totalPages}</span>
      </div>
      <p className="mt-2 text-[7.5px] text-gray-400 italic max-w-[480px]">
        {LABELS[language].disclaimer}
      </p>
    </div>
  );
}

// ─── Parcel Detail Section ───

function ParcelSection({ parcel, language, coordinateSystem: _coordinateSystem }: {
  parcel: PrintableParcel;
  language: PrintLanguage;
  coordinateSystem: PrintCoordinateSystem;
}) {
  const L = LABELS[language];
  const infectionRate = parcel.treesScanned > 0
    ? ((parcel.infectedTrees / parcel.treesScanned) * 100).toFixed(1)
    : '0';

  return (
    <div>
      <SectionTitle>{L.parcelOverview}: {parcel.name}</SectionTitle>

      <KVRow label={L.municipality} value={parcel.municipality} />
      <KVRow label={L.area} value={`${fmtNum(parcel.areaHectares, 1, language)} ${L.hectares}`} />
      <KVRow label={L.lastSurvey} value={fmtDate(parcel.lastSurveyDate, language)} />
      {parcel.standAge && <KVRow label={language === 'sv' ? 'Bestandsalder' : 'Stand Age'} value={`${parcel.standAge} ${language === 'sv' ? 'ar' : 'years'}`} />}

      <div className="grid grid-cols-3 gap-2.5 my-3">
        <HealthGauge score={parcel.healthScore} />
        <div className="border border-gray-200 rounded-lg p-3 text-center">
          <div className="text-lg font-bold font-mono" style={{ color: scoreColor(parcel.healthScore) }}>
            {L[parcel.healthTrend]}
          </div>
          <div className="text-[9px] text-gray-500 uppercase tracking-wide">{L.healthTrend}</div>
        </div>
        <div className="border border-gray-200 rounded-lg p-3 text-center">
          <RiskBadge risk={parcel.beetleRisk} language={language} />
          <div className="text-[9px] text-gray-500 uppercase tracking-wide mt-1">{L.beetleRisk}</div>
        </div>
      </div>

      <SectionTitle>{L.species}</SectionTitle>
      <SpeciesBar speciesMix={parcel.speciesMix} />

      <SectionTitle>{L.detectionSummary}</SectionTitle>
      <KVRow label={L.treesScanned} value={fmtNum(parcel.treesScanned, 0, language)} />
      <KVRow label={L.infectedTrees} value={`${parcel.infectedTrees} (${infectionRate}%)`} />
      <KVRow label={L.deadTrees} value={String(parcel.deadTrees)} />
      <KVRow label={L.ndvi} value={fmtNum(parcel.ndviAvg, 2, language)} />
      <KVRow label={L.timberVolume} value={`${fmtNum(parcel.timberVolumeM3, 0, language)} m\u00B3fub`} />
      <KVRow label={L.timberValue} value={fmtSEK(parcel.timberValueSEK, language)} />
      <KVRow label={L.carbon} value={`${fmtNum(parcel.carbonTonsCO2, 1, language)} ${language === 'sv' ? 'ton' : 'tonnes'} CO\u2082`} />

      {parcel.historicalScores.length > 0 && (
        <>
          <SectionTitle>{L.trend12}</SectionTitle>
          <ScoreTrendChart scores={parcel.historicalScores} />
        </>
      )}

      {parcel.riskFactors.length > 0 && (
        <>
          <SectionTitle>{L.riskFactors}</SectionTitle>
          <ul className="list-none p-0 my-1.5">
            {parcel.riskFactors.map((r, i) => (
              <li key={i} className="py-[3px] pl-4 text-[10.5px] relative before:content-[''] before:absolute before:left-0 before:top-[9px] before:w-1.5 before:h-1.5 before:rounded-full before:bg-amber-500">
                {r}
              </li>
            ))}
          </ul>
        </>
      )}

      {parcel.recommendations.length > 0 && (
        <>
          <SectionTitle>{L.recommendations}</SectionTitle>
          <ul className="list-none p-0 my-1.5">
            {parcel.recommendations.map((r, i) => (
              <li key={i} className="py-[3px] pl-4 text-[10.5px] relative before:content-[''] before:absolute before:left-0 before:top-[9px] before:w-1.5 before:h-1.5 before:rounded-full before:bg-green-600">
                {r}
              </li>
            ))}
          </ul>
        </>
      )}
    </div>
  );
}

// ─── Main Component ───

export default function PrintableReport({
  type,
  parcels,
  language,
  coordinateSystem,
  userName,
  generatedAt,
  surveyId,
  surveyDate,
  droneModel,
}: PrintableReportProps) {
  const L = LABELS[language];
  const title = titleForType(type, language);
  const dateStr = generatedAt ?? new Date().toISOString();

  const totalPages = useMemo(() => {
    switch (type) {
      case 'parcel-summary': return 2;
      case 'portfolio-overview': return 1 + Math.ceil(parcels.length / 3) + 1;
      case 'survey-report': return 2 + parcels.length;
      case 'timber-inventory': return 1 + parcels.length;
      case 'health-assessment': return 2 + parcels.length;
      default: return 2;
    }
  }, [type, parcels.length]);

  const summaryStats = useMemo(() => {
    const totalArea = parcels.reduce((s, p) => s + p.areaHectares, 0);
    const avgHealth = Math.round(parcels.reduce((s, p) => s + p.healthScore, 0) / Math.max(parcels.length, 1));
    const totalVolume = parcels.reduce((s, p) => s + p.timberVolumeM3, 0);
    const totalValue = parcels.reduce((s, p) => s + p.timberValueSEK, 0);
    return { totalArea, avgHealth, totalVolume, totalValue };
  }, [parcels]);

  const headerProps = { language, userName, generatedAt: dateStr };

  return (
    <div className="bg-white text-gray-900 font-sans text-[11px] leading-relaxed print:bg-white">
      <style>{`
        @page { size: A4; margin: 15mm 18mm; }
        @media print {
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          .page-break { page-break-after: always; }
          .page-break:last-child { page-break-after: auto; }
          .no-print { display: none !important; }
        }
      `}</style>

      {/* ═══ Cover Page ═══ */}
      <div className="max-w-[210mm] mx-auto print:max-w-none page-break">
        <ReportHeader {...headerProps} />
        <GreenStripe />

        <h2 className="font-serif text-xl font-bold text-[#166534] mb-1">{title}</h2>
        <p className="text-[11px] text-gray-500 mb-5">
          {parcels.length > 1
            ? `${parcels.length} ${language === 'sv' ? 'skiften' : 'parcels'}`
            : `${parcels[0]?.name ?? ''} \u2014 ${parcels[0]?.municipality ?? ''}`}
          {surveyId && ` | ${L.surveyId}: ${surveyId}`}
        </p>

        {/* Survey details for survey reports */}
        {type === 'survey-report' && (surveyId || droneModel) && (
          <>
            <SectionTitle>{L.surveyDetails}</SectionTitle>
            {surveyId && <KVRow label={L.surveyId} value={surveyId} />}
            {surveyDate && <KVRow label={L.surveyDate} value={fmtDate(surveyDate, language)} />}
            {droneModel && <KVRow label={L.droneModel} value={droneModel} />}
          </>
        )}

        {/* Table of Contents for multi-parcel */}
        {parcels.length > 1 && (
          <>
            <SectionTitle>{L.toc}</SectionTitle>
            <div className="my-2">
              {parcels.map((p, i) => (
                <div key={p.id} className="flex justify-between py-1 border-b border-dotted border-gray-300 text-[11px]">
                  <span className="text-[#166534] font-medium">{p.name} &mdash; {p.municipality}</span>
                  <span className="text-gray-500 font-mono text-[10px]">{i + 2}</span>
                </div>
              ))}
            </div>
          </>
        )}

        {/* Portfolio Summary */}
        {parcels.length > 1 && (
          <>
            <SectionTitle>{L.summary}</SectionTitle>
            <div className="grid grid-cols-3 gap-2.5 my-3">
              <div className="border border-gray-200 rounded-lg p-3 text-center">
                <div className="text-xl font-bold font-mono text-[#166534]">{parcels.length}</div>
                <div className="text-[9px] text-gray-500 uppercase tracking-wide">{L.parcelsIncluded}</div>
              </div>
              <div className="border border-gray-200 rounded-lg p-3 text-center">
                <div className="text-xl font-bold font-mono text-[#166534]">{fmtNum(summaryStats.totalArea, 1, language)}</div>
                <div className="text-[9px] text-gray-500 uppercase tracking-wide">{L.totalArea} (ha)</div>
              </div>
              <HealthGauge score={summaryStats.avgHealth} />
            </div>
            <div className="grid grid-cols-2 gap-2.5 my-3">
              <div className="border border-gray-200 rounded-lg p-3 text-center">
                <div className="text-sm font-bold font-mono text-[#166534]">{fmtNum(summaryStats.totalVolume, 0, language)} m&sup3;fub</div>
                <div className="text-[9px] text-gray-500 uppercase tracking-wide">{L.totalVolume}</div>
              </div>
              <div className="border border-gray-200 rounded-lg p-3 text-center">
                <div className="text-sm font-bold font-mono text-[#166534]">{fmtSEK(summaryStats.totalValue, language)}</div>
                <div className="text-[9px] text-gray-500 uppercase tracking-wide">{L.totalValue}</div>
              </div>
            </div>

            {/* Summary table */}
            <table className="w-full border-collapse my-2 text-[10px]">
              <thead>
                <tr className="bg-gray-100">
                  <th className="text-left p-1.5 font-semibold text-gray-700 border-b-2 border-gray-300 text-[9px] uppercase tracking-wide">
                    {language === 'sv' ? 'Skifte' : 'Parcel'}
                  </th>
                  <th className="text-right p-1.5 font-semibold text-gray-700 border-b-2 border-gray-300 text-[9px] uppercase tracking-wide">{L.area}</th>
                  <th className="text-right p-1.5 font-semibold text-gray-700 border-b-2 border-gray-300 text-[9px] uppercase tracking-wide">{L.healthScore}</th>
                  <th className="text-right p-1.5 font-semibold text-gray-700 border-b-2 border-gray-300 text-[9px] uppercase tracking-wide">{L.timberVolume}</th>
                  <th className="p-1.5 font-semibold text-gray-700 border-b-2 border-gray-300 text-[9px] uppercase tracking-wide">{L.beetleRisk}</th>
                </tr>
              </thead>
              <tbody>
                {parcels.map((p) => (
                  <tr key={p.id} className="border-b border-gray-200">
                    <td className="p-1.5">
                      <strong>{p.name}</strong>
                      <br />
                      <span className="text-[8px] text-gray-500">{p.municipality}</span>
                    </td>
                    <td className="p-1.5 text-right font-mono">{fmtNum(p.areaHectares, 1, language)}</td>
                    <td className="p-1.5 text-right font-mono font-bold" style={{ color: scoreColor(p.healthScore) }}>{p.healthScore}</td>
                    <td className="p-1.5 text-right font-mono">{fmtNum(p.timberVolumeM3, 0, language)}</td>
                    <td className="p-1.5"><RiskBadge risk={p.beetleRisk} language={language} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </>
        )}

        {/* For single-parcel types, show the parcel directly on cover */}
        {parcels.length === 1 && type === 'parcel-summary' && (
          <ParcelSection parcel={parcels[0]} language={language} coordinateSystem={coordinateSystem} />
        )}

        <ReportFooter pageNum={1} totalPages={totalPages} language={language} generatedAt={dateStr} />
      </div>

      {/* ═══ Health Assessment: Risk Overview Page ═══ */}
      {type === 'health-assessment' && parcels.length > 1 && (
        <div className="max-w-[210mm] mx-auto print:max-w-none page-break">
          <ReportHeader {...headerProps} />

          <SectionTitle>{L.riskOverview}</SectionTitle>
          <table className="w-full border-collapse my-2 text-[10px]">
            <thead>
              <tr className="bg-gray-100">
                <th className="text-left p-1.5 font-semibold text-gray-700 border-b-2 border-gray-300 text-[9px] uppercase">{language === 'sv' ? 'Skifte' : 'Parcel'}</th>
                <th className="text-right p-1.5 font-semibold text-gray-700 border-b-2 border-gray-300 text-[9px] uppercase">{L.healthScore}</th>
                <th className="p-1.5 font-semibold text-gray-700 border-b-2 border-gray-300 text-[9px] uppercase">{L.beetleRisk}</th>
                <th className="text-right p-1.5 font-semibold text-gray-700 border-b-2 border-gray-300 text-[9px] uppercase">{L.infectedTrees}</th>
                <th className="text-right p-1.5 font-semibold text-gray-700 border-b-2 border-gray-300 text-[9px] uppercase">{L.infectionRate}</th>
                <th className="p-1.5 font-semibold text-gray-700 border-b-2 border-gray-300 text-[9px] uppercase">{L.healthTrend}</th>
              </tr>
            </thead>
            <tbody>
              {parcels.map((p) => {
                const rate = p.treesScanned > 0 ? ((p.infectedTrees / p.treesScanned) * 100).toFixed(1) : '0';
                return (
                  <tr key={p.id} className="border-b border-gray-200">
                    <td className="p-1.5 font-medium">{p.name}</td>
                    <td className="p-1.5 text-right font-mono font-bold" style={{ color: scoreColor(p.healthScore) }}>{p.healthScore}</td>
                    <td className="p-1.5"><RiskBadge risk={p.beetleRisk} language={language} /></td>
                    <td className="p-1.5 text-right font-mono">{p.infectedTrees}</td>
                    <td className="p-1.5 text-right font-mono">{rate}%</td>
                    <td className="p-1.5">{L[p.healthTrend]}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>

          <ReportFooter pageNum={2} totalPages={totalPages} language={language} generatedAt={dateStr} />
        </div>
      )}

      {/* ═══ Per-Parcel Detail Pages ═══ */}
      {(type !== 'parcel-summary' || parcels.length > 1) && parcels.map((parcel, i) => {
        const pageNum = type === 'health-assessment' ? i + 3 : i + 2;
        const isLast = i === parcels.length - 1;
        return (
          <div key={parcel.id} className={`max-w-[210mm] mx-auto print:max-w-none ${isLast ? '' : 'page-break'}`}>
            <ReportHeader {...headerProps} />
            <ParcelSection parcel={parcel} language={language} coordinateSystem={coordinateSystem} />
            <ReportFooter pageNum={pageNum} totalPages={totalPages} language={language} generatedAt={dateStr} />
          </div>
        );
      })}
    </div>
  );
}
